/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iyuba_concept2_util_RecordUtil */

#ifndef _Included_com_iyuba_concept2_util_RecordUtil
#define _Included_com_iyuba_concept2_util_RecordUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iyuba_concept2_util_RecordUtil_SAMPLE_RATE_IN_HZ
#define com_iyuba_concept2_util_RecordUtil_SAMPLE_RATE_IN_HZ 16000L
/*
 * Class:     com_iyuba_concept2_util_RecordUtil
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_iyuba_concept2_util_RecordUtil_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
